[Feature] Episode Progress Tracking and Resume
ThaUnknown/miru pull request #409
Opened 2024-01-20 20:36 UTC by michielcx

This pull request introduces a new feature that enhances user experience by allowing them to continue watching an episode from where they left off.

Progress of each episode is stored in IndexedDB using Dexie.js. The progress is saved every second, so even when the application closes unexpectedly, the progress is remembered.
Additionally the episode progress is displayed on Card components using halfmoon's progress bar and kept automatically up-to-date with Dexie's liveQuery.

I made this for myself, but I can imagine others like this feature.

2024-01-20 21:41 UTC, ThaUnknown commented
I don't fuck with your description as it looks AI generated as fuck

I fuck with this code tho, a lot, it's clean, but you really dont need to use dexie.js, localstorage should be more than enough, maybe even consider using cache store so it times out old progress for you? it's definitely not a needed dependency

Media can fail to resolve, you shouldn't track progress when that happens: https://github.com/ThaUnknown/miru/blob/master/common/modules/animeresolver.js#L206
the code for this isn't clean so read at your own risk lol

Do you handle moments when there's no file media? that can sometimes happen when a person plays a file called `myvideo.mkv` Miru won't resolve what media it is, and all the metadata for the now playing media will either use old media, or no media at all

the currently media code is so scuffed it's not even funny, so I'm not sure myself what happens, I haven't time to re-write it

2024-01-20 21:41 UTC, ThaUnknown commented on common/modules/animeprogress.js
> +export const db = new Dexie('miru');
IDB is overkill for this, the amt of data is tiny

2024-01-20 21:42 UTC, ThaUnknown commented on common/modules/animeprogress.js
> +export async function setAnimeProgress ({mediaId, episode, currentTime, safeduration}) {
this data should expire after say 3 months or so, maybe consider using cache storage?

2024-01-20 21:42 UTC, ThaUnknown commented on common/views/Player/Player.svelte
> +    const mediaId = current?.media?.media?.id
if current.media.failed don't load.

2024-01-20 21:42 UTC, ThaUnknown commented on common/views/Player/Player.svelte
> +  function saveAnimeProgress () {
if current.media.failed don't save.

2024-01-20 21:43 UTC, ThaUnknown commented on common/views/ViewAnime/EpisodeList.svelte
> +  import { liveAnimeProgress } from "@/modules/animeprogress";
don't use extensionless import

2024-01-20 21:44 UTC, ThaUnknown commented on common/components/cards/PreviewCard.svelte
> +      {#if progress && $progress > 0}
how does this look?

2024-01-20 21:44 UTC, ThaUnknown commented on common/components/cards/EpisodePreviewCard.svelte
> +    {#if progress && $progress > 0}
how does this look? screenshots pls

2024-01-20 21:44 UTC, ThaUnknown commented on common/components/cards/EpisodeCard.svelte
> +      {#if progress && $progress > 0}
how does this look? screenshots pls

2024-01-20 21:44 UTC, ThaUnknown requested changes
not bad

2024-01-20 22:22 UTC, ThaUnknown commented
additionally I considered using anilist anime notes, see notes under medialist: https://anilist.github.io/ApiV2-GraphQL-Docs

this would solve the entire "how to save this locally", and also show data across devices which is important

I thought of using [3y3 encoding](https://github.com/ArjixWasTaken/3y3/blob/main/3y3.js), this would allow to append data to notes [if the user already has their own] without overriding it, while also making sure it doesn't impact anilist's UI since it's not visible

2024-01-21 02:38 UTC, EnergoStalin commented on common/views/ViewAnime/EpisodeList.svelte
> +  import { liveAnimeProgress } from "@/modules/animeprogress";
Eslint enforce when?
```json
{
  "rules": {
    "import/extensions": [
      "error",
      "ignorePackages",
      {
        "js": "always",
        "ts": "always",
        "svelte": "always"
      }
    ]
  },
}
```

2024-01-21 03:28 UTC, michielcx commented
Alright Dexie.js is gone, it works with local storage now. I guess cache storage could have worked too but that kind of focuses on caching requests and responses so I think local storage is better suited. Though instead of using expiry the local storage is limited to the latest 1000 episodes (~0.12MB). 

I don't know how to play a local file like `myvideo.mkv` so I haven't tested it. But it compares current.media and media's id and episode to make sure they're the same and truthy. I am guessing that solves some of those problems.

We could make a background task that syncs the changes from local storage to anilist, but that's a future feature I guess?

Here are some screenshots of the progress bar, mind you I am no designer, so feel free to make it look better:

Episode Card:
<img width="160" alt="1" src="https://github.com/ThaUnknown/miru/assets/4696621/700c83c9-890e-4925-b2bc-f23578ec5487">
Episode Card (hovered):
<img width="180" alt="2" src="https://github.com/ThaUnknown/miru/assets/4696621/25e9d55e-07e5-423f-9d9e-7175e9af0ed0">
Small Card:
<img width="129" alt="3" src="https://github.com/ThaUnknown/miru/assets/4696621/671c8fb4-fac4-4544-a847-5e5d67239e79">
Small Card (hovered):
<img width="151" alt="4" src="https://github.com/ThaUnknown/miru/assets/4696621/def8651a-8c83-454b-a1d4-ed5228f49176">
Episode List:
<img width="325" alt="5" src="https://github.com/ThaUnknown/miru/assets/4696621/2263af91-c828-44ff-95a0-6cf6a7dc4d21">

Let me know if there's something else

2024-01-21 12:49 UTC, ThaUnknown commented
hover cards and small card looks bad, I probably wouldn't keep that

2024-01-21 16:05 UTC, ThaUnknown commented on common/components/cards/SmallCard.svelte
> +    {#if progress && $progress > 0}
progress is always a store, so the first check does nothing

2024-01-21 16:06 UTC, ThaUnknown commented on common/components/cards/SmallCard.svelte
> +    {#if progress && $progress > 0}
I'd remove this from small cards, it's missleading as users might think its anime watch progress, not episode watch progress

2024-01-21 16:06 UTC, ThaUnknown commented on common/components/cards/PreviewCard.svelte
> +      {#if progress && $progress > 0}
I'd remove this from small cards, it's missleading as users might think its anime watch progress, not episode watch progress

2024-01-21 16:07 UTC, ThaUnknown commented on common/components/cards/EpisodeCard.svelte
> +      {#if progress && $progress > 0}
progress is a store, which is always truthy so the first condition is useless

2024-01-21 16:07 UTC, ThaUnknown commented on common/components/cards/EpisodePreviewCard.svelte
> +    {#if progress && $progress > 0}
progress is a store, which is always truthy so the first condition is useless

2024-01-21 16:08 UTC, ThaUnknown commented on common/modules/animeprogress.js
> +  return derived(animeProgressStore, (data) => {
I have no clue what derived stores do, never used them, but it's nice seeing them used :)

2024-01-21 16:09 UTC, ThaUnknown commented on common/views/Player/Player.svelte
> +  setInterval(saveAnimeProgress, 1000)
this is a lot of code and operations to run on a 1s interval, especially considering we seek back 5 seconds anyways so the accuracy is low, I'd set this to 15 maybe 30 seconds?

2024-01-21 16:12 UTC, ThaUnknown commented on common/views/Player/Player.svelte
> +    if (current?.media.failed || mediaId !== media?.media?.id || episode !== media?.episode) return
this condition is fucking awful, you have 11 branches in a single if statement!!!!!!!!!!!

this is NOT human readable!

at the start of theses functionns I'd add a guard clause
```js
if (!current?.media?.media?.id || !current.media.media.episode || current.media.failed || !media?.media?.id || !media.episode) return
```
and then remove all the subsequent nullish chaining, that will make it x100 more readable

2024-01-21 16:13 UTC, ThaUnknown requested changes
address these and I think this is ready to be shipped

2024-01-21 16:15 UTC, ThaUnknown commented
also I've noticed your commits use a different email than the account that's the author of this PR, I assume because you don't want torrent related things linked to your main account, feel free to address that if it's an issue, the PR can be 1 commit if you override/squash it, I don't mind

2024-02-02 10:13 UTC, merged