Introduce custom title bar
ThaUnknown/miru pull request #520
Opened 2024-08-30 20:35 UTC by onkofonko

Introduce a configurable custom title bar.
Editable using CSS
![Screenshot 2024-08-30 223413](https://github.com/user-attachments/assets/c207fbc9-d86e-46a7-a0f7-d22115454b65)
![image](https://github.com/user-attachments/assets/9ccb569c-273e-4737-9977-2491c60a9c6d)

2024-08-30 20:36 UTC, SManyac commented
Nice

2024-08-31 16:20 UTC, ThaUnknown commented
this is nice, however:
- needs to be tested on windows 10
- needs to be tested on mac
- needs to be tested on linux
- you're using the wrong code styling, use Miru's ESLint config

2024-08-31 16:22 UTC, ThaUnknown requested changes
needs further review and styling fixes

2024-08-31 16:50 UTC, onkofonko commented
Will test on various systems and correct code styling.

2024-09-01 12:37 UTC, onkofonko commented
Unfortunately, I cannot test on MacOS as I don't have a MacOS device available to build or test.
Linux (Ubuntu):
https://github.com/user-attachments/assets/ffeb1c87-6be1-45b1-91f7-ab7d10294b09

Windows 10:

2024-09-01 16:08 UTC, onkofonko commented
Unfortunately, I can't test MacOS Build as I don't own a MacOS device, so I can't even build it.

Linux (Ubuntu):

https://github.com/user-attachments/assets/20b4b9e0-a9fe-4149-9c19-dd1b853e7ee7

Windows 10: 

https://github.com/user-attachments/assets/e53c189a-c761-4337-b44f-fb6b571cae0a

2024-09-02 12:21 UTC, ThaUnknown requested changes
close but not quite, this is really nice tho

2024-09-02 12:21 UTC, ThaUnknown commented on common/components/Menubar.svelte
> +      stringify: (e) => e
there's no reason to change the styling on these

2024-09-02 12:21 UTC, ThaUnknown commented on common/components/Menubar.svelte
> +    window.ipcRenderer.send('closeapp')
im fairly sure miru already implements this functionality

2024-09-02 12:21 UTC, ThaUnknown commented on common/components/Menubar.svelte
> +    --navbar-height: 32px !important;
why 32px?

2024-09-02 12:21 UTC, ThaUnknown commented on common/components/Menubar.svelte
> +    z-index: 101 !important;
don't restyle code you havent changed

2024-09-02 12:21 UTC, ThaUnknown commented on common/components/Menubar.svelte
> +  #window-controls {
dont use ids, use classes

2024-09-02 12:21 UTC, ThaUnknown commented on electron/src/main/app.js
> +      contextIsolation: true,
this should be in a separate PR, with an explanation, it's out of scope for this PR

2024-09-02 12:21 UTC, ThaUnknown commented on electron/src/main/app.js
> +  const focusedWindow = BrowserWindow.getFocusedWindow()
absolutely not, miru already defines ways to read ipc messages for the main window, this is not the way of doing it

2024-09-02 12:21 UTC, ThaUnknown commented on electron/src/preload/preload.js
> +contextBridge.exposeInMainWorld('ipcRenderer', {
no, you're repeating the code above, miru already exposes this functionality via `IPC`

2024-09-04 18:03 UTC, onkofonko commented
I will address all the comments within the next few days.

2024-09-04 18:05 UTC, onkofonko commented on common/components/Menubar.svelte
> +    --navbar-height: 32px !important;
The standard title bar has a height of 32px.
Source: https://learn.microsoft.com/en-us/windows/apps/design/basics/titlebar-design

2024-09-05 14:59 UTC, onkofonko commented
Retested on Windows 11, Windows 10 and Ubuntu

2024-09-05 15:38 UTC, ThaUnknown commented on electron/src/main/app.js
> +    ipcMain.on('minimize', () => BrowserWindow.getFocusedWindow()?.minimize())
this should be this.mainWindow

2024-09-05 15:38 UTC, ThaUnknown commented on common/components/Menubar.svelte
> +    grid-template-columns: repeat(3, 46px);
is there any reason grid is used here? or is it simply easier to work with?

2024-09-05 15:42 UTC, ThaUnknown requested changes
i think the minimize and maximize buttons should also have a slightly transparent hover background, just like the close button, this is a really nice change

2024-09-05 15:43 UTC, onkofonko commented
> i think the minimize and maximize buttons should also have a slightly transparent hover background, just like the close button, this is a really nice change

Would you like the hover color to be an accent color?

2024-09-05 15:44 UTC, onkofonko commented on common/components/Menubar.svelte
> +    grid-template-columns: repeat(3, 46px);
It can also be display:flex

2024-09-05 15:48 UTC, ThaUnknown commented
i think its best to keep it accurate to windows, so some semi-transparent white

2024-09-05 17:10 UTC, onkofonko commented
> i think its best to keep it accurate to windows, so some semi-transparent white

dark background: 
![image](https://github.com/user-attachments/assets/7a9bdcd7-2936-4a55-89a7-3fcd044ce93b)

light background: 
![image](https://github.com/user-attachments/assets/df06c197-5958-4b49-9b68-bdbe9bbfd174)

The best thing would be to make the hover effect and icon colors reactive, but I'm not sure how to do it without affecting the close button's hover color

2024-09-05 17:46 UTC, ThaUnknown commented on common/components/Menubar.svelte
>    <div class='h-full bg-dark flex-grow-1'>
this div is now empty, is it needed?

2024-09-05 17:47 UTC, ThaUnknown commented on common/components/Menubar.svelte
> +    display: flex;
i think all of these styles can be instead used as bootstrap's atomic clasess:
```css
d-flex position-absolute top-0 right-0 height-full
```

2024-09-05 17:47 UTC, ThaUnknown commented on common/components/Menubar.svelte
> +    color: #ffffff;
same as above, border-0 color-white and i think the grid row can go?

2024-09-05 18:09 UTC, ThaUnknown approved these changes
lgtm

2024-09-07 07:13 UTC, ThaUnknown commented
this is good to go, but i'm currently on vacation, so I cannot merge this until I get back next month

2024-09-07 11:40 UTC, onkofonko commented
No problem. Have fun on your vacation.

2024-10-11 12:02 UTC, merged